// Content Studio — team color tokens.
//
// Switching a graphic from a Red Sox post to a Bruins post should be picking a
// different team, not editing a layout. Every sports template pulls its colors
// from here and nowhere else.
//
// Keyed `league-abbr` rather than plain abbreviation on purpose: the Red Sox
// and the Bruins are both "BOS". Collapsing them would make the Sox render in
// black and gold the first time somebody added hockey.
//
// These are TEAM colors, deliberately separate from the Townies brand tokens in
// design.ts. Red Sox navy is #0C2340; Townies navy is #0D1B2A. Close enough to
// look like a typo, different enough to look wrong on a jersey.

export type League = 'mlb' | 'nhl' | 'nba' | 'nfl';

export const LEAGUE_LABELS: Record<League, string> = {
  mlb: 'MLB',
  nhl: 'NHL',
  nba: 'NBA',
  nfl: 'NFL',
};

export type TeamPalette = {
  id: string;
  league: League;
  /** "Boston" */
  city: string;
  /** "Red Sox" */
  name: string;
  /** "BOS" — what shows in the matchup box when no logo loads. */
  abbr: string;
  /** Dominant color. Fills the wordmark rail and module accents. */
  primary: string;
  /** Supporting color. Accent rules, secondary type. */
  secondary: string;
  /** Readable text color on top of `primary`. */
  onPrimary: string;
  /** Remote logo. Pre-resolved to a data URI at render time; falls back to abbr. */
  logoUrl?: string;
};

const espnLogo = (league: League, abbr: string) =>
  `https://a.espncdn.com/i/teamlogos/${league}/500/${abbr.toLowerCase()}.png`;

/**
 * All 124 teams across MLB, NHL, NBA and NFL.
 *
 * Generated from ESPN's own team endpoint so every id, abbreviation and logo
 * URL matches what the schedule feed returns — auto-fill would otherwise hand
 * back games whose teams have no palette and render as "TBD".
 *
 * The Boston four and their most-posted rivals are hand-curated from official
 * brand guidelines and deliberately override the generated values: ESPN lists
 * the Celtics' secondary as plain white and the Red Sox navy a shade light.
 *
 * `secondary` is always the ON-DARK accent — it drives the wordmark rail and
 * every rule on the graphic. For generated teams it's the brighter of ESPN's
 * two colors, falling back to white when both are dark, so a wordmark can
 * never come out invisible.
 */
/**
 * All 124 teams across MLB, NHL, NBA and NFL.
 *
 * Generated from ESPN's own team endpoint so every id, abbreviation and logo
 * URL matches what the schedule feed returns — auto-fill would otherwise hand
 * back games whose teams have no palette and render as "TBD".
 *
 * The Boston four and their most-posted rivals are hand-curated from official
 * brand guidelines and override the generated values: ESPN lists the Celtics'
 * secondary as plain white and the Red Sox navy a shade light.
 *
 * `secondary` is ALWAYS the on-dark accent — it drives the wordmark rail, the
 * labels and every rule on the graphic. It is chosen by WCAG contrast against
 * the scrim (not luminance: Red Sox red is dark by luminance yet perfectly
 * legible, while Orioles black is invisible), falling back to the primary and
 * then to white. Curated entries go through the same check — the Orioles
 * shipped a black, unreadable wordmark until they did.
 */
export const TEAM_COLORS: Record<string, TeamPalette> = {
  // ---- Boston first: the four teams this account actually lives on. ----
  'mlb-bos': {
    id: 'mlb-bos',
    league: 'mlb',
    city: "Boston",
    name: "Red Sox",
    abbr: 'BOS',
    primary: '#0C2340',
    secondary: '#BD3039',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('mlb', 'BOS'),
  },
  'nhl-bos': {
    id: 'nhl-bos',
    league: 'nhl',
    city: "Boston",
    name: "Bruins",
    abbr: 'BOS',
    primary: '#000000',
    secondary: '#FFB81C',
    onPrimary: '#FFB81C',
    logoUrl: espnLogo('nhl', 'BOS'),
  },
  'nba-bos': {
    id: 'nba-bos',
    league: 'nba',
    city: "Boston",
    name: "Celtics",
    abbr: 'BOS',
    primary: '#007A33',
    secondary: '#BA9653',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nba', 'BOS'),
  },
  'nfl-ne': {
    id: 'nfl-ne',
    league: 'nfl',
    city: "New England",
    name: "Patriots",
    abbr: 'NE',
    primary: '#002244',
    secondary: '#C60C30',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nfl', 'NE'),
  },

  // ---- MLB ----
  'mlb-ari': {
    id: 'mlb-ari',
    league: 'mlb',
    city: "Arizona",
    name: "Diamondbacks",
    abbr: 'ARI',
    primary: '#AA182C',
    secondary: '#AA182C',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('mlb', 'ARI'),
  },
  'mlb-ath': {
    id: 'mlb-ath',
    league: 'mlb',
    city: "Athletics",
    name: "Athletics",
    abbr: 'ATH',
    primary: '#003831',
    secondary: '#EFB21E',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('mlb', 'ATH'),
  },
  'mlb-atl': {
    id: 'mlb-atl',
    league: 'mlb',
    city: "Atlanta",
    name: "Braves",
    abbr: 'ATL',
    primary: '#0C2340',
    secondary: '#BA0C2F',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('mlb', 'ATL'),
  },
  'mlb-bal': {
    id: 'mlb-bal',
    league: 'mlb',
    city: "Baltimore",
    name: "Orioles",
    abbr: 'BAL',
    primary: '#DF4601',
    secondary: '#DF4601',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('mlb', 'BAL'),
  },
  'mlb-chc': {
    id: 'mlb-chc',
    league: 'mlb',
    city: "Chicago",
    name: "Cubs",
    abbr: 'CHC',
    primary: '#0E3386',
    secondary: '#CC3433',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('mlb', 'CHC'),
  },
  'mlb-chw': {
    id: 'mlb-chw',
    league: 'mlb',
    city: "Chicago",
    name: "White Sox",
    abbr: 'CHW',
    primary: '#000000',
    secondary: '#C4CED4',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('mlb', 'CHW'),
  },
  'mlb-cin': {
    id: 'mlb-cin',
    league: 'mlb',
    city: "Cincinnati",
    name: "Reds",
    abbr: 'CIN',
    primary: '#C6011F',
    secondary: '#FFFFFF',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('mlb', 'CIN'),
  },
  'mlb-cle': {
    id: 'mlb-cle',
    league: 'mlb',
    city: "Cleveland",
    name: "Guardians",
    abbr: 'CLE',
    primary: '#002B5C',
    secondary: '#E31937',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('mlb', 'CLE'),
  },
  'mlb-col': {
    id: 'mlb-col',
    league: 'mlb',
    city: "Colorado",
    name: "Rockies",
    abbr: 'COL',
    primary: '#33006F',
    secondary: '#FFFFFF',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('mlb', 'COL'),
  },
  'mlb-det': {
    id: 'mlb-det',
    league: 'mlb',
    city: "Detroit",
    name: "Tigers",
    abbr: 'DET',
    primary: '#0A2240',
    secondary: '#FF4713',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('mlb', 'DET'),
  },
  'mlb-hou': {
    id: 'mlb-hou',
    league: 'mlb',
    city: "Houston",
    name: "Astros",
    abbr: 'HOU',
    primary: '#002D62',
    secondary: '#EB6E1F',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('mlb', 'HOU'),
  },
  'mlb-kc': {
    id: 'mlb-kc',
    league: 'mlb',
    city: "Kansas City",
    name: "Royals",
    abbr: 'KC',
    primary: '#004687',
    secondary: '#7AB2DD',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('mlb', 'KC'),
  },
  'mlb-laa': {
    id: 'mlb-laa',
    league: 'mlb',
    city: "Los Angeles",
    name: "Angels",
    abbr: 'LAA',
    primary: '#BA0021',
    secondary: '#C4CED4',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('mlb', 'LAA'),
  },
  'mlb-lad': {
    id: 'mlb-lad',
    league: 'mlb',
    city: "Los Angeles",
    name: "Dodgers",
    abbr: 'LAD',
    primary: '#005A9C',
    secondary: '#FFFFFF',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('mlb', 'LAD'),
  },
  'mlb-mia': {
    id: 'mlb-mia',
    league: 'mlb',
    city: "Miami",
    name: "Marlins",
    abbr: 'MIA',
    primary: '#00A3E0',
    secondary: '#00A3E0',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('mlb', 'MIA'),
  },
  'mlb-mil': {
    id: 'mlb-mil',
    league: 'mlb',
    city: "Milwaukee",
    name: "Brewers",
    abbr: 'MIL',
    primary: '#13294B',
    secondary: '#FFC72C',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('mlb', 'MIL'),
  },
  'mlb-min': {
    id: 'mlb-min',
    league: 'mlb',
    city: "Minnesota",
    name: "Twins",
    abbr: 'MIN',
    primary: '#031F40',
    secondary: '#E20E32',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('mlb', 'MIN'),
  },
  'mlb-nym': {
    id: 'mlb-nym',
    league: 'mlb',
    city: "New York",
    name: "Mets",
    abbr: 'NYM',
    primary: '#002D72',
    secondary: '#FF5910',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('mlb', 'NYM'),
  },
  'mlb-nyy': {
    id: 'mlb-nyy',
    league: 'mlb',
    city: "New York",
    name: "Yankees",
    abbr: 'NYY',
    primary: '#132448',
    secondary: '#C4CED4',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('mlb', 'NYY'),
  },
  'mlb-phi': {
    id: 'mlb-phi',
    league: 'mlb',
    city: "Philadelphia",
    name: "Phillies",
    abbr: 'PHI',
    primary: '#E81828',
    secondary: '#E81828',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('mlb', 'PHI'),
  },
  'mlb-pit': {
    id: 'mlb-pit',
    league: 'mlb',
    city: "Pittsburgh",
    name: "Pirates",
    abbr: 'PIT',
    primary: '#000000',
    secondary: '#FDB827',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('mlb', 'PIT'),
  },
  'mlb-sd': {
    id: 'mlb-sd',
    league: 'mlb',
    city: "San Diego",
    name: "Padres",
    abbr: 'SD',
    primary: '#2F241D',
    secondary: '#FFC425',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('mlb', 'SD'),
  },
  'mlb-sea': {
    id: 'mlb-sea',
    league: 'mlb',
    city: "Seattle",
    name: "Mariners",
    abbr: 'SEA',
    primary: '#005C5C',
    secondary: '#FFFFFF',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('mlb', 'SEA'),
  },
  'mlb-sf': {
    id: 'mlb-sf',
    league: 'mlb',
    city: "San Francisco",
    name: "Giants",
    abbr: 'SF',
    primary: '#000000',
    secondary: '#FD5A1E',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('mlb', 'SF'),
  },
  'mlb-stl': {
    id: 'mlb-stl',
    league: 'mlb',
    city: "St. Louis",
    name: "Cardinals",
    abbr: 'STL',
    primary: '#BE0A14',
    secondary: '#BE0A14',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('mlb', 'STL'),
  },
  'mlb-tb': {
    id: 'mlb-tb',
    league: 'mlb',
    city: "Tampa Bay",
    name: "Rays",
    abbr: 'TB',
    primary: '#092C5C',
    secondary: '#8FBCE6',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('mlb', 'TB'),
  },
  'mlb-tex': {
    id: 'mlb-tex',
    league: 'mlb',
    city: "Texas",
    name: "Rangers",
    abbr: 'TEX',
    primary: '#003278',
    secondary: '#C0111F',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('mlb', 'TEX'),
  },
  'mlb-tor': {
    id: 'mlb-tor',
    league: 'mlb',
    city: "Toronto",
    name: "Blue Jays",
    abbr: 'TOR',
    primary: '#134A8E',
    secondary: '#E8291C',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('mlb', 'TOR'),
  },
  'mlb-wsh': {
    id: 'mlb-wsh',
    league: 'mlb',
    city: "Washington",
    name: "Nationals",
    abbr: 'WSH',
    primary: '#AB0003',
    secondary: '#FFFFFF',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('mlb', 'WSH'),
  },

  // ---- NHL ----
  'nhl-ana': {
    id: 'nhl-ana',
    league: 'nhl',
    city: "Anaheim",
    name: "Ducks",
    abbr: 'ANA',
    primary: '#FC4C02',
    secondary: '#FC4C02',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nhl', 'ANA'),
  },
  'nhl-buf': {
    id: 'nhl-buf',
    league: 'nhl',
    city: "Buffalo",
    name: "Sabres",
    abbr: 'BUF',
    primary: '#00468B',
    secondary: '#FDB71A',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nhl', 'BUF'),
  },
  'nhl-car': {
    id: 'nhl-car',
    league: 'nhl',
    city: "Carolina",
    name: "Hurricanes",
    abbr: 'CAR',
    primary: '#E30426',
    secondary: '#E30426',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nhl', 'CAR'),
  },
  'nhl-cbj': {
    id: 'nhl-cbj',
    league: 'nhl',
    city: "Columbus",
    name: "Blue Jackets",
    abbr: 'CBJ',
    primary: '#002D62',
    secondary: '#E31937',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nhl', 'CBJ'),
  },
  'nhl-cgy': {
    id: 'nhl-cgy',
    league: 'nhl',
    city: "Calgary",
    name: "Flames",
    abbr: 'CGY',
    primary: '#DD1A32',
    secondary: '#DD1A32',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nhl', 'CGY'),
  },
  'nhl-chi': {
    id: 'nhl-chi',
    league: 'nhl',
    city: "Chicago",
    name: "Blackhawks",
    abbr: 'CHI',
    primary: '#E31937',
    secondary: '#E31937',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nhl', 'CHI'),
  },
  'nhl-col': {
    id: 'nhl-col',
    league: 'nhl',
    city: "Colorado",
    name: "Avalanche",
    abbr: 'COL',
    primary: '#860038',
    secondary: '#005EA3',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nhl', 'COL'),
  },
  'nhl-dal': {
    id: 'nhl-dal',
    league: 'nhl',
    city: "Dallas",
    name: "Stars",
    abbr: 'DAL',
    primary: '#20864C',
    secondary: '#20864C',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nhl', 'DAL'),
  },
  'nhl-det': {
    id: 'nhl-det',
    league: 'nhl',
    city: "Detroit",
    name: "Red Wings",
    abbr: 'DET',
    primary: '#E30526',
    secondary: '#FFFFFF',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nhl', 'DET'),
  },
  'nhl-edm': {
    id: 'nhl-edm',
    league: 'nhl',
    city: "Edmonton",
    name: "Oilers",
    abbr: 'EDM',
    primary: '#00205B',
    secondary: '#FF4C00',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nhl', 'EDM'),
  },
  'nhl-fla': {
    id: 'nhl-fla',
    league: 'nhl',
    city: "Florida",
    name: "Panthers",
    abbr: 'FLA',
    primary: '#E51937',
    secondary: '#E51937',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nhl', 'FLA'),
  },
  'nhl-la': {
    id: 'nhl-la',
    league: 'nhl',
    city: "Los Angeles",
    name: "Kings",
    abbr: 'LA',
    primary: '#121212',
    secondary: '#A2AAAD',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nhl', 'LA'),
  },
  'nhl-min': {
    id: 'nhl-min',
    league: 'nhl',
    city: "Minnesota",
    name: "Wild",
    abbr: 'MIN',
    primary: '#124734',
    secondary: '#AE122A',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nhl', 'MIN'),
  },
  'nhl-mtl': {
    id: 'nhl-mtl',
    league: 'nhl',
    city: "Montreal",
    name: "Canadiens",
    abbr: 'MTL',
    primary: '#AF1E2D',
    secondary: '#AF1E2D',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nhl', 'MTL'),
  },
  'nhl-nj': {
    id: 'nhl-nj',
    league: 'nhl',
    city: "New Jersey",
    name: "Devils",
    abbr: 'NJ',
    primary: '#E30B2B',
    secondary: '#E30B2B',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nhl', 'NJ'),
  },
  'nhl-nsh': {
    id: 'nhl-nsh',
    league: 'nhl',
    city: "Nashville",
    name: "Predators",
    abbr: 'NSH',
    primary: '#FDBA31',
    secondary: '#FDBA31',
    onPrimary: '#0D1B2A',
    logoUrl: espnLogo('nhl', 'NSH'),
  },
  'nhl-nyi': {
    id: 'nhl-nyi',
    league: 'nhl',
    city: "New York",
    name: "Islanders",
    abbr: 'NYI',
    primary: '#00529B',
    secondary: '#F47D31',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nhl', 'NYI'),
  },
  'nhl-nyr': {
    id: 'nhl-nyr',
    league: 'nhl',
    city: "New York",
    name: "Rangers",
    abbr: 'NYR',
    primary: '#0056AE',
    secondary: '#E51937',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nhl', 'NYR'),
  },
  'nhl-ott': {
    id: 'nhl-ott',
    league: 'nhl',
    city: "Ottawa",
    name: "Senators",
    abbr: 'OTT',
    primary: '#DD1A32',
    secondary: '#B79257',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nhl', 'OTT'),
  },
  'nhl-phi': {
    id: 'nhl-phi',
    league: 'nhl',
    city: "Philadelphia",
    name: "Flyers",
    abbr: 'PHI',
    primary: '#FE5823',
    secondary: '#FE5823',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nhl', 'PHI'),
  },
  'nhl-pit': {
    id: 'nhl-pit',
    league: 'nhl',
    city: "Pittsburgh",
    name: "Penguins",
    abbr: 'PIT',
    primary: '#000000',
    secondary: '#FDB71A',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nhl', 'PIT'),
  },
  'nhl-sea': {
    id: 'nhl-sea',
    league: 'nhl',
    city: "Seattle",
    name: "Kraken",
    abbr: 'SEA',
    primary: '#000D33',
    secondary: '#A3DCE4',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nhl', 'SEA'),
  },
  'nhl-sj': {
    id: 'nhl-sj',
    league: 'nhl',
    city: "San Jose",
    name: "Sharks",
    abbr: 'SJ',
    primary: '#00788A',
    secondary: '#00788A',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nhl', 'SJ'),
  },
  'nhl-stl': {
    id: 'nhl-stl',
    league: 'nhl',
    city: "St. Louis",
    name: "Blues",
    abbr: 'STL',
    primary: '#0070B9',
    secondary: '#FDB71A',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nhl', 'STL'),
  },
  'nhl-tb': {
    id: 'nhl-tb',
    league: 'nhl',
    city: "Tampa Bay",
    name: "Lightning",
    abbr: 'TB',
    primary: '#003E7E',
    secondary: '#FFFFFF',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nhl', 'TB'),
  },
  'nhl-tor': {
    id: 'nhl-tor',
    league: 'nhl',
    city: "Toronto",
    name: "Maple Leafs",
    abbr: 'TOR',
    primary: '#00205B',
    secondary: '#FFFFFF',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nhl', 'TOR'),
  },
  'nhl-utah': {
    id: 'nhl-utah',
    league: 'nhl',
    city: "Utah",
    name: "Mammoth",
    abbr: 'UTAH',
    primary: '#000000',
    secondary: '#7AB2E1',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nhl', 'UTAH'),
  },
  'nhl-van': {
    id: 'nhl-van',
    league: 'nhl',
    city: "Vancouver",
    name: "Canucks",
    abbr: 'VAN',
    primary: '#003E7E',
    secondary: '#008752',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nhl', 'VAN'),
  },
  'nhl-vgk': {
    id: 'nhl-vgk',
    league: 'nhl',
    city: "Vegas",
    name: "Golden Knights",
    abbr: 'VGK',
    primary: '#344043',
    secondary: '#B4975A',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nhl', 'VGK'),
  },
  'nhl-wpg': {
    id: 'nhl-wpg',
    league: 'nhl',
    city: "Winnipeg",
    name: "Jets",
    abbr: 'WPG',
    primary: '#002D62',
    secondary: '#C41230',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nhl', 'WPG'),
  },
  'nhl-wsh': {
    id: 'nhl-wsh',
    league: 'nhl',
    city: "Washington",
    name: "Capitals",
    abbr: 'WSH',
    primary: '#D71830',
    secondary: '#D71830',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nhl', 'WSH'),
  },

  // ---- NBA ----
  'nba-atl': {
    id: 'nba-atl',
    league: 'nba',
    city: "Atlanta",
    name: "Hawks",
    abbr: 'ATL',
    primary: '#C8102E',
    secondary: '#FDB927',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nba', 'ATL'),
  },
  'nba-bkn': {
    id: 'nba-bkn',
    league: 'nba',
    city: "Brooklyn",
    name: "Nets",
    abbr: 'BKN',
    primary: '#000000',
    secondary: '#FFFFFF',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nba', 'BKN'),
  },
  'nba-cha': {
    id: 'nba-cha',
    league: 'nba',
    city: "Charlotte",
    name: "Hornets",
    abbr: 'CHA',
    primary: '#008CA8',
    secondary: '#008CA8',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nba', 'CHA'),
  },
  'nba-chi': {
    id: 'nba-chi',
    league: 'nba',
    city: "Chicago",
    name: "Bulls",
    abbr: 'CHI',
    primary: '#CE1141',
    secondary: '#CE1141',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nba', 'CHI'),
  },
  'nba-cle': {
    id: 'nba-cle',
    league: 'nba',
    city: "Cleveland",
    name: "Cavaliers",
    abbr: 'CLE',
    primary: '#860038',
    secondary: '#BC945C',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nba', 'CLE'),
  },
  'nba-dal': {
    id: 'nba-dal',
    league: 'nba',
    city: "Dallas",
    name: "Mavericks",
    abbr: 'DAL',
    primary: '#0064B1',
    secondary: '#BBC4CA',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nba', 'DAL'),
  },
  'nba-den': {
    id: 'nba-den',
    league: 'nba',
    city: "Denver",
    name: "Nuggets",
    abbr: 'DEN',
    primary: '#0E2240',
    secondary: '#FEC524',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nba', 'DEN'),
  },
  'nba-det': {
    id: 'nba-det',
    league: 'nba',
    city: "Detroit",
    name: "Pistons",
    abbr: 'DET',
    primary: '#1D428A',
    secondary: '#C8102E',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nba', 'DET'),
  },
  'nba-gs': {
    id: 'nba-gs',
    league: 'nba',
    city: "Golden State",
    name: "Warriors",
    abbr: 'GS',
    primary: '#FDB927',
    secondary: '#FDB927',
    onPrimary: '#0D1B2A',
    logoUrl: espnLogo('nba', 'GS'),
  },
  'nba-hou': {
    id: 'nba-hou',
    league: 'nba',
    city: "Houston",
    name: "Rockets",
    abbr: 'HOU',
    primary: '#CE1141',
    secondary: '#CE1141',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nba', 'HOU'),
  },
  'nba-ind': {
    id: 'nba-ind',
    league: 'nba',
    city: "Indiana",
    name: "Pacers",
    abbr: 'IND',
    primary: '#0C2340',
    secondary: '#FFD520',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nba', 'IND'),
  },
  'nba-lac': {
    id: 'nba-lac',
    league: 'nba',
    city: "LA",
    name: "Clippers",
    abbr: 'LAC',
    primary: '#12173F',
    secondary: '#C8102E',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nba', 'LAC'),
  },
  'nba-lal': {
    id: 'nba-lal',
    league: 'nba',
    city: "Los Angeles",
    name: "Lakers",
    abbr: 'LAL',
    primary: '#552583',
    secondary: '#FDB927',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nba', 'LAL'),
  },
  'nba-mem': {
    id: 'nba-mem',
    league: 'nba',
    city: "Memphis",
    name: "Grizzlies",
    abbr: 'MEM',
    primary: '#5D76A9',
    secondary: '#5D76A9',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nba', 'MEM'),
  },
  'nba-mia': {
    id: 'nba-mia',
    league: 'nba',
    city: "Miami",
    name: "Heat",
    abbr: 'MIA',
    primary: '#98002E',
    secondary: '#FFFFFF',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nba', 'MIA'),
  },
  'nba-mil': {
    id: 'nba-mil',
    league: 'nba',
    city: "Milwaukee",
    name: "Bucks",
    abbr: 'MIL',
    primary: '#00471B',
    secondary: '#EEE1C6',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nba', 'MIL'),
  },
  'nba-min': {
    id: 'nba-min',
    league: 'nba',
    city: "Minnesota",
    name: "Timberwolves",
    abbr: 'MIN',
    primary: '#266092',
    secondary: '#79BC43',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nba', 'MIN'),
  },
  'nba-no': {
    id: 'nba-no',
    league: 'nba',
    city: "New Orleans",
    name: "Pelicans",
    abbr: 'NO',
    primary: '#0A2240',
    secondary: '#B4975A',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nba', 'NO'),
  },
  'nba-ny': {
    id: 'nba-ny',
    league: 'nba',
    city: "New York",
    name: "Knicks",
    abbr: 'NY',
    primary: '#006BB6',
    secondary: '#F58426',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nba', 'NY'),
  },
  'nba-okc': {
    id: 'nba-okc',
    league: 'nba',
    city: "Oklahoma City",
    name: "Thunder",
    abbr: 'OKC',
    primary: '#007AC1',
    secondary: '#EF3B24',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nba', 'OKC'),
  },
  'nba-orl': {
    id: 'nba-orl',
    league: 'nba',
    city: "Orlando",
    name: "Magic",
    abbr: 'ORL',
    primary: '#0150B5',
    secondary: '#9CA0A3',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nba', 'ORL'),
  },
  'nba-phi': {
    id: 'nba-phi',
    league: 'nba',
    city: "Philadelphia",
    name: "76ers",
    abbr: 'PHI',
    primary: '#1D428A',
    secondary: '#E01234',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nba', 'PHI'),
  },
  'nba-phx': {
    id: 'nba-phx',
    league: 'nba',
    city: "Phoenix",
    name: "Suns",
    abbr: 'PHX',
    primary: '#29127A',
    secondary: '#E56020',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nba', 'PHX'),
  },
  'nba-por': {
    id: 'nba-por',
    league: 'nba',
    city: "Portland",
    name: "Trail Blazers",
    abbr: 'POR',
    primary: '#E03A3E',
    secondary: '#E03A3E',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nba', 'POR'),
  },
  'nba-sa': {
    id: 'nba-sa',
    league: 'nba',
    city: "San Antonio",
    name: "Spurs",
    abbr: 'SA',
    primary: '#000000',
    secondary: '#C4CED4',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nba', 'SA'),
  },
  'nba-sac': {
    id: 'nba-sac',
    league: 'nba',
    city: "Sacramento",
    name: "Kings",
    abbr: 'SAC',
    primary: '#5A2D81',
    secondary: '#6A7A82',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nba', 'SAC'),
  },
  'nba-tor': {
    id: 'nba-tor',
    league: 'nba',
    city: "Toronto",
    name: "Raptors",
    abbr: 'TOR',
    primary: '#D91244',
    secondary: '#D91244',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nba', 'TOR'),
  },
  'nba-utah': {
    id: 'nba-utah',
    league: 'nba',
    city: "Utah",
    name: "Jazz",
    abbr: 'UTAH',
    primary: '#4E008E',
    secondary: '#79A3DC',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nba', 'UTAH'),
  },
  'nba-wsh': {
    id: 'nba-wsh',
    league: 'nba',
    city: "Washington",
    name: "Wizards",
    abbr: 'WSH',
    primary: '#E31837',
    secondary: '#E31837',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nba', 'WSH'),
  },

  // ---- NFL ----
  'nfl-ari': {
    id: 'nfl-ari',
    league: 'nfl',
    city: "Arizona",
    name: "Cardinals",
    abbr: 'ARI',
    primary: '#A40227',
    secondary: '#FFFFFF',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nfl', 'ARI'),
  },
  'nfl-atl': {
    id: 'nfl-atl',
    league: 'nfl',
    city: "Atlanta",
    name: "Falcons",
    abbr: 'ATL',
    primary: '#A71930',
    secondary: '#A71930',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nfl', 'ATL'),
  },
  'nfl-bal': {
    id: 'nfl-bal',
    league: 'nfl',
    city: "Baltimore",
    name: "Ravens",
    abbr: 'BAL',
    primary: '#29126F',
    secondary: '#FFFFFF',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nfl', 'BAL'),
  },
  'nfl-buf': {
    id: 'nfl-buf',
    league: 'nfl',
    city: "Buffalo",
    name: "Bills",
    abbr: 'BUF',
    primary: '#00338D',
    secondary: '#C60C30',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nfl', 'BUF'),
  },
  'nfl-car': {
    id: 'nfl-car',
    league: 'nfl',
    city: "Carolina",
    name: "Panthers",
    abbr: 'CAR',
    primary: '#0085CA',
    secondary: '#0085CA',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nfl', 'CAR'),
  },
  'nfl-chi': {
    id: 'nfl-chi',
    league: 'nfl',
    city: "Chicago",
    name: "Bears",
    abbr: 'CHI',
    primary: '#0B1C3A',
    secondary: '#E64100',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nfl', 'CHI'),
  },
  'nfl-cin': {
    id: 'nfl-cin',
    league: 'nfl',
    city: "Cincinnati",
    name: "Bengals",
    abbr: 'CIN',
    primary: '#FB4F14',
    secondary: '#FB4F14',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nfl', 'CIN'),
  },
  'nfl-cle': {
    id: 'nfl-cle',
    league: 'nfl',
    city: "Cleveland",
    name: "Browns",
    abbr: 'CLE',
    primary: '#472A08',
    secondary: '#FF3C00',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nfl', 'CLE'),
  },
  'nfl-dal': {
    id: 'nfl-dal',
    league: 'nfl',
    city: "Dallas",
    name: "Cowboys",
    abbr: 'DAL',
    primary: '#002A5C',
    secondary: '#B0B7BC',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nfl', 'DAL'),
  },
  'nfl-den': {
    id: 'nfl-den',
    league: 'nfl',
    city: "Denver",
    name: "Broncos",
    abbr: 'DEN',
    primary: '#0A2343',
    secondary: '#FC4C02',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nfl', 'DEN'),
  },
  'nfl-det': {
    id: 'nfl-det',
    league: 'nfl',
    city: "Detroit",
    name: "Lions",
    abbr: 'DET',
    primary: '#0076B6',
    secondary: '#BBBBBB',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nfl', 'DET'),
  },
  'nfl-gb': {
    id: 'nfl-gb',
    league: 'nfl',
    city: "Green Bay",
    name: "Packers",
    abbr: 'GB',
    primary: '#204E32',
    secondary: '#FFB612',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nfl', 'GB'),
  },
  'nfl-hou': {
    id: 'nfl-hou',
    league: 'nfl',
    city: "Houston",
    name: "Texans",
    abbr: 'HOU',
    primary: '#021018',
    secondary: '#EB0028',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nfl', 'HOU'),
  },
  'nfl-ind': {
    id: 'nfl-ind',
    league: 'nfl',
    city: "Indianapolis",
    name: "Colts",
    abbr: 'IND',
    primary: '#003B75',
    secondary: '#FFFFFF',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nfl', 'IND'),
  },
  'nfl-jax': {
    id: 'nfl-jax',
    league: 'nfl',
    city: "Jacksonville",
    name: "Jaguars",
    abbr: 'JAX',
    primary: '#007487',
    secondary: '#D7A22A',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nfl', 'JAX'),
  },
  'nfl-kc': {
    id: 'nfl-kc',
    league: 'nfl',
    city: "Kansas City",
    name: "Chiefs",
    abbr: 'KC',
    primary: '#E31837',
    secondary: '#FFB612',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nfl', 'KC'),
  },
  'nfl-lac': {
    id: 'nfl-lac',
    league: 'nfl',
    city: "Los Angeles",
    name: "Chargers",
    abbr: 'LAC',
    primary: '#0080C6',
    secondary: '#FFC20E',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nfl', 'LAC'),
  },
  'nfl-lar': {
    id: 'nfl-lar',
    league: 'nfl',
    city: "Los Angeles",
    name: "Rams",
    abbr: 'LAR',
    primary: '#003594',
    secondary: '#FFD100',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nfl', 'LAR'),
  },
  'nfl-lv': {
    id: 'nfl-lv',
    league: 'nfl',
    city: "Las Vegas",
    name: "Raiders",
    abbr: 'LV',
    primary: '#000000',
    secondary: '#A5ACAF',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nfl', 'LV'),
  },
  'nfl-mia': {
    id: 'nfl-mia',
    league: 'nfl',
    city: "Miami",
    name: "Dolphins",
    abbr: 'MIA',
    primary: '#008E97',
    secondary: '#FC4C02',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nfl', 'MIA'),
  },
  'nfl-min': {
    id: 'nfl-min',
    league: 'nfl',
    city: "Minnesota",
    name: "Vikings",
    abbr: 'MIN',
    primary: '#4F2683',
    secondary: '#FFC62F',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nfl', 'MIN'),
  },
  'nfl-no': {
    id: 'nfl-no',
    league: 'nfl',
    city: "New Orleans",
    name: "Saints",
    abbr: 'NO',
    primary: '#D3BC8D',
    secondary: '#D3BC8D',
    onPrimary: '#0D1B2A',
    logoUrl: espnLogo('nfl', 'NO'),
  },
  'nfl-nyg': {
    id: 'nfl-nyg',
    league: 'nfl',
    city: "New York",
    name: "Giants",
    abbr: 'NYG',
    primary: '#003C7F',
    secondary: '#C9243F',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nfl', 'NYG'),
  },
  'nfl-nyj': {
    id: 'nfl-nyj',
    league: 'nfl',
    city: "New York",
    name: "Jets",
    abbr: 'NYJ',
    primary: '#125740',
    secondary: '#FFFFFF',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nfl', 'NYJ'),
  },
  'nfl-phi': {
    id: 'nfl-phi',
    league: 'nfl',
    city: "Philadelphia",
    name: "Eagles",
    abbr: 'PHI',
    primary: '#06424D',
    secondary: '#FFFFFF',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nfl', 'PHI'),
  },
  'nfl-pit': {
    id: 'nfl-pit',
    league: 'nfl',
    city: "Pittsburgh",
    name: "Steelers",
    abbr: 'PIT',
    primary: '#000000',
    secondary: '#FFB612',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nfl', 'PIT'),
  },
  'nfl-sea': {
    id: 'nfl-sea',
    league: 'nfl',
    city: "Seattle",
    name: "Seahawks",
    abbr: 'SEA',
    primary: '#002A5C',
    secondary: '#69BE28',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nfl', 'SEA'),
  },
  'nfl-sf': {
    id: 'nfl-sf',
    league: 'nfl',
    city: "San Francisco",
    name: "49ers",
    abbr: 'SF',
    primary: '#AA0000',
    secondary: '#B3995D',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nfl', 'SF'),
  },
  'nfl-tb': {
    id: 'nfl-tb',
    league: 'nfl',
    city: "Tampa Bay",
    name: "Buccaneers",
    abbr: 'TB',
    primary: '#BD1C36',
    secondary: '#BD1C36',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nfl', 'TB'),
  },
  'nfl-ten': {
    id: 'nfl-ten',
    league: 'nfl',
    city: "Tennessee",
    name: "Titans",
    abbr: 'TEN',
    primary: '#4495D2',
    secondary: '#4495D2',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nfl', 'TEN'),
  },
  'nfl-wsh': {
    id: 'nfl-wsh',
    league: 'nfl',
    city: "Washington",
    name: "Commanders",
    abbr: 'WSH',
    primary: '#5A1414',
    secondary: '#FFB612',
    onPrimary: '#FFFFFF',
    logoUrl: espnLogo('nfl', 'WSH'),
  },
};

/** Fallback so an unknown team id can never blank out a render. */
export const FALLBACK_TEAM: TeamPalette = {
  id: 'unknown',
  league: 'mlb',
  city: '',
  name: 'Team',
  abbr: 'TBD',
  primary: '#0D1B2A',
  secondary: '#8F918D',
  onPrimary: '#FFFFFF',
};

export function getTeam(id: string | undefined | null): TeamPalette {
  if (!id) return FALLBACK_TEAM;
  return TEAM_COLORS[id] ?? FALLBACK_TEAM;
}

/**
 * Options for the studio's team picker. Pass a league to scope the list to that
 * sport — the studio's League selector does exactly this, and the league prefix
 * is then dropped from each label because the whole list is already that league.
 */
export function teamOptions(league?: League): { value: string; label: string }[] {
  const teams = Object.values(TEAM_COLORS).filter((t) => !league || t.league === league);
  return teams.map((t) => ({
    value: t.id,
    label: league ? `${t.city} ${t.name}` : `${LEAGUE_LABELS[t.league]} · ${t.city} ${t.name}`,
  }));
}

/** League options for the studio's League selector, in a fixed order. */
export const LEAGUE_OPTIONS: { value: League; label: string }[] = (
  Object.keys(LEAGUE_LABELS) as League[]
).map((l) => ({ value: l, label: LEAGUE_LABELS[l] }));

/** Third odds-row label, per sport — mirrors the auto-fill route's LINE_LABEL. */
export const LEAGUE_LINE_LABEL: Record<League, string> = {
  mlb: 'Run Line',
  nhl: 'Puck Line',
  nba: 'Spread',
  nfl: 'Spread',
};

/** The league a team id belongs to (falls back to the fallback team's league). */
export function leagueOf(id: string | undefined | null): League {
  return getTeam(id).league;
}

/**
 * First team of a league. Boston leads the table, so this returns the Boston
 * side by default; `exclude` keeps a home/away pair from landing on one team.
 */
export function firstTeamId(league: League, exclude?: string): string {
  const t = Object.values(TEAM_COLORS).find((x) => x.league === league && x.id !== exclude);
  return t ? t.id : FALLBACK_TEAM.id;
}

/**
 * Re-tag the leading "MLB · " league token in a venue line to match a new
 * league. A hand-written venue that carries no league token is left untouched.
 */
export function swapVenueLeague(venue: string, league: League): string {
  const tokens = Object.values(LEAGUE_LABELS).join('|');
  const re = new RegExp(`^(?:${tokens})\\s*·\\s*`);
  return re.test(venue) ? venue.replace(re, `${LEAGUE_LABELS[league]} · `) : venue;
}
